# Deploy Docs to GitHub Pages using MkDocs
# This workflow builds documentation from the 'docs/' folder using mkdocs.yml in the repo root
# and deploys the static site to GitHub Pages.

name: Build Docs and Push Site

on:
  push:
    branches:
      - main

jobs:
  build-and-push-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # Ensure mkdocs.yml exists in the repo root
      - name: Check for mkdocs.yml in root
        run: |
          if [ ! -f mkdocs.yml ]; then
            echo "Error: mkdocs.yml not found in repository root. Please add it." && exit 1
          fi
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Build docs with MkDocs
        run: |
          mkdocs build
      - name: Push site/ to site-artifact branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Create orphan branch or switch to it
          git checkout --orphan site-artifact
          # Remove all files (tracked and untracked)
          git rm -rf . || true
          rm -rf *
          # Copy site output to root
          cp -r site/* .
          # Add a .nojekyll file to prevent GitHub Pages from ignoring files/folders starting with _
          touch .nojekyll
          git add .
          # Only commit if there are files to commit
          if git diff --cached --quiet; then
            echo 'No changes to commit'
          else
            git commit -m "Update built site from main"
            git push --force origin site-artifact
          fi 